### ISSUE TITLE
Ubuntu: "Error: java.net.UnknownServiceException: Unable to find acceptable protocols."

### ISSUE THREAD

**Issue by j4r3kb** [btdex/btdex#161]
Ubuntu 18.04,
Btdex 0.4.8
New installation

```
java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 8.0.6.5 - pxa6480sr6fp5-20200111_02(SR6 FP5))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200108_436782 (JIT enabled, AOT enabled)
OpenJ9   - 7d1059c
OMR      - d059105
IBM      - c8aee39)
JCL - 20200110_01 based on Oracle jdk8u241-b07
```

![image](https://user-images.githubusercontent.com/16531572/118775594-6173b200-b887-11eb-9556-dedb8fedaa01.png)

**Comment by jjos2372** [comment]
Hello, thank you for reporting. This was a temporary issue with that particular node. It is now fixed, but in case of this kind of issue you can select another node on the bottom left button.

**Comment by j4r3kb** [comment]
I believe it is other case. The issue persists on my end, no matter which node I choose in bottom left corner.

**Comment by jjos2372** [comment]
I just tested some here and no issue on my end. Maybe something with your java truststore certificate. Is this a standard Java install? Also be sure to wait a minute or two every time you switch nodes or to quit and restart. We can reopen to investigate more if that does not fix it.

**Comment by j4r3kb** [comment]
I did not install anything special related to Java, standard Ubuntu 18.04 installation.
If there are some command to verify/reinstall Java I can run them if you could point me to some docs.
I waited/restarted already. Happens on every node.

![image](https://user-images.githubusercontent.com/16531572/118806901-eb337780-b8a7-11eb-9677-212ba7b6722d.png)

How can I verify Java truststore or SSL settings?

**Comment by jjos2372** [comment]
I see you have java8 and that should be fine, perhaps try openjdk-11-jre and make sure that is your default Java to see if that improves.
